name: Feature Request
description: Suggest an idea for AndroidIRCX
title: "[Feature]: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: "Thanks for the suggestion. Please describe the feature and its value."
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
    validations:
      required: false