/*
 * Copyright (c) 2025-2026 Velimir Majstorov
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import type {
  ThemeMessageFormats,
  MessageFormatPart,
} from '../../services/ThemeService';
import type { FormatPalette } from './types';
import { tx } from '../../i18n/localization';

const t = (key: string) => tx.t(key);

/**
 * The "IRcap bars" message-format look — `[hh:mm] nick ¦ message` with
 * directional arrows and bracketed hostmasks — generalized from the built-in
 * IRcap theme so any theme can adopt it by supplying its own colours.
 *
 * Every colour comes from the supplied {@link FormatPalette}; nothing is
 * hardcoded, so the preset is fully theme-agnostic.
 */
export const makeIrcapBarsFormats = (p: FormatPalette): ThemeMessageFormats => {
  // Body colour: honour an explicit palette body colour, otherwise inherit the
  // theme's messageText by leaving the token unstyled.
  const bodyStyle = p.message ? { color: p.message } : undefined;
  const messageToken: MessageFormatPart = bodyStyle
    ? { type: 'token', value: 'message', style: bodyStyle }
    : { type: 'token', value: 'message' };

  return {
    message: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'nick', style: { color: p.nick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '¦', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      messageToken,
    ],
    messageMention: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'nick', style: { color: p.nick, bold: true } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '¦', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      messageToken,
    ],
    action: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '*', style: { color: p.action } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'nick', style: { color: p.action } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '¦', style: { color: p.action } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'message', style: { color: p.action } },
    ],
    actionMention: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '*', style: { color: p.action, bold: false } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'nick', style: { color: p.action, bold: true } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '¦', style: { color: p.action, bold: false } },
      { type: 'text', value: ' ', style: {} },
      {
        type: 'token',
        value: 'message',
        style: { color: p.action, bold: false },
      },
    ],
    notice: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '-', style: { bold: false, color: p.notice } },
      { type: 'text', value: '(', style: { bold: true, color: p.notice } },
      { type: 'token', value: 'nick', style: { color: p.notice } },
      { type: 'text', value: ')', style: { bold: true, color: p.notice } },
      { type: 'text', value: '-', style: { color: p.notice } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: '-', style: { color: p.notice } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'message', style: { color: p.notice } },
    ],
    event: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
      { type: 'text', value: ' => ', style: { color: p.punctuation } },
      { type: 'text', value: '¦ ', style: { color: p.punctuation } },
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'message', style: { color: p.event } },
      { type: 'text', value: ']', style: { color: p.punctuation } },
    ],
    join: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '->', style: { color: p.join } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted, bold: true } },
      { type: 'text', value: ' [', style: { color: p.join } },
      { type: 'token', value: 'username', style: { color: p.muted } },
      { type: 'text', value: '@', style: { color: p.join } },
      { type: 'token', value: 'hostname', style: { color: p.muted } },
      { type: 'text', value: ']', style: { color: p.join } },
      { type: 'text', value: ` ${t('enters')}`, style: { color: p.muted } },
    ],
    part: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '<-', style: { color: p.part } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      { type: 'text', value: ' [', style: { color: p.part } },
      { type: 'token', value: 'username', style: { color: p.muted } },
      { type: 'text', value: '@', style: { color: p.part } },
      { type: 'token', value: 'hostname', style: { color: p.muted } },
      { type: 'text', value: ']', style: { color: p.part } },
      { type: 'text', value: ` ${t('leaves')}`, style: { color: p.muted } },
    ],
    quit: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '<-', style: { color: p.quit } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      { type: 'text', value: ' [', style: { color: p.quit } },
      { type: 'token', value: 'username', style: { color: p.muted } },
      { type: 'text', value: '@', style: { color: p.quit } },
      { type: 'token', value: 'hostname', style: { color: p.muted } },
      { type: 'text', value: ']', style: { color: p.quit } },
      { type: 'text', value: ` ${t('closes')}`, style: { color: p.muted } },
    ],
    kick: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '=>', style: { color: p.punctuation } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'target', style: { color: p.kick } },
      {
        type: 'text',
        value: ` ${t('kicked_by')} `,
        style: { color: p.muted },
      },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      { type: 'text', value: ' [', style: { color: p.punctuation } },
      { type: 'token', value: 'reason', style: { color: p.muted } },
      { type: 'text', value: ' ]', style: { color: p.punctuation } },
    ],
    nick: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '=>', style: { color: p.nickChange } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      {
        type: 'token',
        value: 'oldnick',
        style: { color: p.muted, bold: true },
      },
      {
        type: 'text',
        value: ` ${t('now_known_as')} `,
        style: { color: p.muted },
      },
      { type: 'token', value: 'newnick', style: { color: p.nickChange } },
    ],
    invite: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '-', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      { type: 'text', value: '(', style: { color: p.punctuation } },
      { type: 'token', value: 'username', style: { color: p.muted } },
      { type: 'text', value: '@', style: { color: p.punctuation } },
      { type: 'token', value: 'hostname', style: { color: p.muted } },
      { type: 'text', value: ')', style: { color: p.punctuation } },
      { type: 'text', value: '- ', style: { color: p.punctuation } },
      {
        type: 'text',
        value: ` ${t('invites_you_to')} `,
        style: { color: p.muted },
      },
      { type: 'token', value: 'channel', style: { bold: true } },
    ],
    monitor: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '=> ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.punctuation } },
      {
        type: 'text',
        value: ` ${t('joined_monitor_list')}`,
        style: { color: p.nick },
      },
    ],
    mode: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '=>', style: { color: p.punctuation } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      { type: 'text', value: ` ${t('sets_mode')}`, style: { color: p.muted } },
      { type: 'text', value: ' [', style: { color: p.punctuation } },
      { type: 'token', value: 'mode', style: { color: p.muted } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'account', style: { color: p.muted } },
      { type: 'text', value: ' ', style: {} },
      { type: 'text', value: ']', style: { color: p.punctuation } },
    ],
    topic: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '=>', style: { color: p.punctuation } },
      { type: 'text', value: ' ¦ ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.muted } },
      {
        type: 'text',
        value: ` ${t('sets_topic')}: `,
        style: { color: p.muted },
      },
      { type: 'token', value: 'message', style: {} },
    ],
    raw: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '*** ', style: {} },
      { type: 'text', value: 'RAW ', style: {} },
      { type: 'token', value: 'numeric', style: {} },
      { type: 'text', value: ':', style: {} },
      { type: 'text', value: '* ', style: {} },
      messageToken,
    ],
    whois: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '|--> ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.nick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'username', style: { color: p.muted } },
      { type: 'text', value: '@', style: { color: p.muted } },
      { type: 'token', value: 'hostname', style: { color: p.muted } },
      { type: 'text', value: ' : ', style: { color: p.punctuation } },
      { type: 'token', value: 'message', style: {} },
    ],
    who: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '|--> ', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.nick } },
      { type: 'text', value: ' [', style: { color: p.punctuation } },
      { type: 'token', value: 'userhost', style: { color: p.muted } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'token', value: 'message', style: {} },
    ],
    names: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '-> Nicks on ', style: { color: p.punctuation } },
      { type: 'token', value: 'channel', style: { color: p.nick } },
      { type: 'text', value: ': ', style: { color: p.punctuation } },
      { type: 'token', value: 'owners', style: { color: p.kick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'admins', style: { color: p.kick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'ops', style: { color: p.kick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'halfops', style: { color: p.kick } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'voices', style: { color: p.event } },
      { type: 'text', value: ' ', style: {} },
      { type: 'token', value: 'normal', style: { color: p.event } },
    ],
    error: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.muted } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      messageToken,
    ],
    ctcp: [
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'time', style: { color: p.timestamp } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      { type: 'text', value: '--> ', style: { color: p.punctuation } },
      { type: 'text', value: 'CTCP ', style: { color: p.nick } },
      { type: 'text', value: '[', style: { color: p.punctuation } },
      { type: 'token', value: 'nick', style: { color: p.punctuation } },
      { type: 'text', value: '] ', style: { color: p.punctuation } },
      messageToken,
    ],
  };
};
